services:
  - type: web
    name: sistema-os-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-os-db
          property: connectionString

  - type: web
    name: sistema-os-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: sistema-os-db
    databaseName: sistema_os
    user: sistema_os_user